name: Create Starline
run-name: "Create Starline for ${{ github.event.inputs.repository }}"

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true

concurrency:
  group: ${{ github.event.inputs.repository }}

jobs:
  create-starline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Add starline to step summary
        run: |
          target='${{ github.event.inputs.repository }}'
          if [[ $target == users/* ]]
          then
            echo "[$target](https://github.com/${target#users/})" >> $GITHUB_STEP_SUMMARY
          elif [[ $target == gists/* ]]
            echo "[$target](https://gist.github.com/${target#gists/})" >> $GITHUB_STEP_SUMMARY
          else
            echo "[$target](https://github.com/$target)' >> $GITHUB_STEP_SUMMARY
          fi
      - run: node create-starline.js ${{ github.event.inputs.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_GITHUB_TOKEN: ${{ secrets.GIST_GITHUB_TOKEN }}
      
      - name: Add starline to step summary
        run: echo '[![starline](https://starlines.qoo.monster/assets/${{ github.event.inputs.repository }})](https://github.com/qoomon/starline/releases/tag/starlines)' >> $GITHUB_STEP_SUMMARY
    
      - uses: actions/upload-artifact@v4
        with:
          path: starlines
